travis:
  secure:
    BINSTAR_TOKEN: dCEfQ/cLu7tLujoLiOGEhlklh9BRfGEBKMU7M7HErhY6vzgvcj26ABN5abJrcXfS56MiUUG+nwoV6Hw6qX4CQWxFLHPmA9SQFYv53za43ntPqIKYfkDZ1AxnyH3R/KDYNikAX/eyxMBcHrUBU5ZnH9dfSR1FfpqFFuLekicLUV2KBGAGBlmSIg9eX8TsvN9L6FmbPbSGJu/kE/J7tSlSCir8i3jOkHuXDlzeBJgE5cV0cW0LdWVP2A09ULF80cRgUAuUGCJerngvTijZNhdrBrez8ehvtpDyDAunNBnAJbfaXlA/WtmBO5ys7SoMjdqhkyjOb7cM5VSsihi8YTY/YqfelELIxepBlnSR944XRClm0jjv9GkSYv3i+anVunC2+abbR5SrWqJk/irPVw0kzcqFoamCEK9tDSuSiCspcQj/XgJtLpy2uRuhN8XjD9pJgAeNRInEL1LidBn+kZ3y3FZP0N2CwvuJSef9bJRibDpJoXvdGy/f23EE9nFSuyZk8hUOYdFeHtIlSFbAJm6e6dNGAGni85oWdGwSLhnsrZDvU6gzEUVVdOoVfc+3NHe8e36bXhxLrQ0ONJNhvN6KUonmxkZ3VYP0W+ZvNJlaPK/pTn+XWCFqOHKNbRJAjEg2qaPgtvxDu8iAYLyU6/kJbXaIzZkUug+v6wNGEx8D8Pg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
