travis:
  secure:
    BINSTAR_TOKEN: Bq6q4vd+KcqtYQcd0b2X5AFdUOOPScjm8O9+mZwVgFYI5xxP6jy67jOD+ySBZ29I/ID5KltN3Z+qUwJhx1l3IZBG888eIHDT2+faApSSDPkNGU/Bk8hQ9zz/PEoRZ79FqG3kx5U86szqXrFEsVbkXiZcelcqAu1kfjAT8PR+MVpMF0G5pA/vvdM1+9Cc9k35JFLKFSopAtrayXiKRhZ7Z23LS5YIJOFlkdXmdeMwgnFrkGArn2BgWthxz+VvqbVJInahr0pND+2IWDXGGNc86f6ugBZyMsYYVHe5Z37gwRCNKhHYWrPrWjNVAO6pegs6Pc/FqxtFqd08pdRYK7Xm4Jfgcql3QJT4LzEPmLpA4M9ncJIUHzg/uOCIKIQ7DS0ohdmUqbrVHlpwGMxSnDf1Hx8FjPzsYJWiEsf5ehehjWxRwkoGBqr23ijkuUU4IZePeSD2kckPwNUfwrO+ddKZRgtOuSlFO0uD34fUtxLc8ZuCRxt38oVyPAvgJsoBC/PK2A5sRWzYRc+mGG/aWhTi3AaZbrUwFaHZsb8bcV+MVE8xUamcpAyqUeu5E1d2sDU8nYf7LYqHmxQuvHY8G+Vnbu39AKgLaONFsX0nq96tW3q0Zi1BFTT6bLftLHhstyi/3N4Pxs2RKNnUgpjBlxbN3rKyjpGbTismprfokjcVdhI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
