travis:
  secure:
    BINSTAR_TOKEN: g7VUeHbAI7BU6paUtbvMZLjPeGCyj+1G15VDaZJVPmfBOFvM2Y5wDyyEJ4A9AqaOj8GCb8eJFeKnMRRAFse6QpqTlfWrCeLoyKs1LRunP4VLIVZUyDmltewMCdpsBU1PbJKh0p3euQnruE3M/vKZOHiRXBkKejnG1L38WMjn3Gq7a1hN5caca3S05vQQezbAm7OyCbIPyE3wco8jClhvAqafx8LmSjlc0kOsK6A/nj5SK/2fEh6nnpjxTCajpngnRMMlKFWEhdxaAhvkscEyOJBr875mx7E57HsjxDmfxuZ0wYZDTdlWAhMowbRUY5438w1NtkklavKZ+3eS5OAwPQsIx/YA7iT5Rjsq2GOUgtqwMCNBd9AMfigifCZq1W89siBSmedG+p8HMa7kSpP8Qun6XOP/koYZ9qURs+5sVqI86DvNpOsPABkjw/1w1ZvVgdy1dcVW3cHx7FAXPqyw2sgvmDfqh0wB8Qe9v2mHQmSVY6cc7lnJNZFffsiy0r45RgLVmRdrzuNQBSmhqMnzb6ebo8RcYM99fbCfK+lpsLv5SS9mgiBTo39YrbxsvYIFXxXjAJXIzgId0SmnDkP6CDlHjvpxlPHdHSNDjhRXBIAlB2EaLDmN3YriTGMX1LghSRc8uch/FghJURW69ko7RWeEgWNK5ZAMS36C6aRXFY8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
